image: fommil/docker-openjdk-sbt:latest
variables:
  SBT_TASK_LIMIT: "4"
  COURSIER_CACHE: "${CI_PROJECT_DIR}/project/.sbt/coursier"

stages:
  - build
  - deploy

build_job:
  stage: build
  except:
    - master
  cache:
    key: default
    paths:
      - project/.sbt
    policy: pull
  script:
    - if $(git grep -qE "TODO|FIXME" *) ; then
        echo "Please remove TODO or FIXME." ;
        exit 1 ;
      fi
    - sbt ";+check ;+cpl ;+lint ;+doc ;+test ;+test:doc"
    - cd scalafix ; sbt tests/test

deploy_job:
  only:
    - master
  except:
    - tags
  stage: deploy
  cache:
    key: default
    paths:
      - project/.sbt
  script:
    - sbt ";+update;+publish"
    - cd scalafix ; sbt update
